[green_agent]
agentbeats_id = "019d0482-d3d5-7622-904a-e9cef7c53d9e"
env = {}

[[participants]]
agentbeats_id = ""
name = "agent"
env = { AGENT_LLM = "openai/gpt-4o-mini", OPENAI_API_KEY = "${OPENAI_API_KEY}", GEMINI_API_KEY = "${GEMINI_API_KEY}" }
