[green_agent]
agentbeats_id = "019d76c2-3bb7-7652-b932-76ad868837b0"
env = {}

[[participants]]
agentbeats_id = ""
name = "agent"
env = { AGENT_LLM = "openai/gpt-4o-mini", OPENAI_API_KEY = "${OPENAI_API_KEY}", GEMINI_API_KEY = "${GEMINI_API_KEY}" }
